// Generated by rumahl-ui-contracts. Do not edit by hand.
export const SNAPSHOT_VERSION = 1 as const;
export const UI_CONTRACT_VERSION = 1 as const;
export const EXTENSION_API_VERSION = 1 as const;

export type WindowChromeVariant = "standard" | "compact";
export type ExtensionSlot = "dashboard_widgets";
export type ThemeTokenId =
  | "color.canvas.background"
  | "color.panel.background"
  | "color.text.primary"
  | "color.text.muted"
  | "color.accent.primary"
  | "color.window.titlebar.background"
  | "color.window.titlebar.foreground"
  | "radius.window"
  | "space.shell.gap";
export type ThemeVariantId = "window.chrome";

export interface ThemeManifestV1 {
  manifestVersion: 1;
  uiContractVersion: typeof UI_CONTRACT_VERSION;
  id: string;
  name: string;
  tokens?: Partial<Record<ThemeTokenId, string>>;
  variants?: Partial<Record<ThemeVariantId, WindowChromeVariant>>;
}

export interface ShellUser {
  displayName: string;
  locale: string;
}

export interface ShellTheme {
  stylesheetUrl: `/shell/themes/sha256-${string}.css`;
  windowChrome: WindowChromeVariant;
}

export type SystemProtectionStatus = "active" | "attention";

export interface ShellSystemStatus {
  protection: SystemProtectionStatus;
  installedAppCount: number;
  observedAtUnixMs: number;
  lastActivityAtUnixMs: number | null;
}

export type ExtensionContribution =
  | {
      kind: "command";
      id: string;
      title: string;
      capability: string;
    }
  | {
      kind: "search_provider";
      id: string;
      title: string;
      capability: string;
    }
  | {
      kind: "widget";
      id: string;
      title: string;
      slot: ExtensionSlot;
      entrypoint: string;
    };

export interface ShellSnapshotV1 {
  snapshotVersion: typeof SNAPSHOT_VERSION;
  uiContractVersion: typeof UI_CONTRACT_VERSION;
  extensionApiVersion: typeof EXTENSION_API_VERSION;
  shellBuildId: string;
  revision: string;
  user: ShellUser;
  theme: ShellTheme;
  systemStatus: ShellSystemStatus;
  contributions: readonly ExtensionContribution[];
}
