const TYPESCRIPT_CONTRACTS_V1: &str = r#"// Generated by rumahl-ui-contracts. Do not edit by hand.
export const SNAPSHOT_VERSION = 1 as const;
export const UI_CONTRACT_VERSION = 1 as const;
export const EXTENSION_API_VERSION = 1 as const;

export type ShellMode = "desktop" | "launcher";
export type WindowChromeVariant = "standard" | "compact";
export type ShellLayoutVariant = "dock" | "taskbar";
export type LauncherLayoutVariant = "springboard" | "drawer";
export type ExtensionSlot = "dashboard_widgets";
export type ThemeTokenId =
  | "color.canvas.background"
  | "color.panel.background"
  | "color.text.primary"
  | "color.text.muted"
  | "color.accent.primary"
  | "color.window.titlebar.background"
  | "color.window.titlebar.foreground"
  | "radius.window"
  | "space.shell.gap"
  | "color.accent"
  | "color.accent.strong"
  | "color.surface"
  | "color.surface.strong"
  | "color.outline"
  | "color.on.wallpaper"
  | "color.on.accent"
  | "color.shadow"
  | "material.blur"
  | "material.saturation"
  | "material.opacity"
  | "shape.radius.dock"
  | "shape.radius.icon"
  | "shape.icon.size"
  | "shape.icon.size.large"
  | "motion.duration"
  | "motion.duration.fast"
  | "motion.easing.spring"
  | "layout.dock.offset"
  | "icon.gradient"
  | "texture.wallpaper"
  | "typography.family"
  | "typography.scale";
export type ThemeVariantId = "window.chrome" | "shell.layout" | "launcher.layout";
export type ThemeVariantValue = WindowChromeVariant | ShellLayoutVariant | LauncherLayoutVariant;

export interface ThemeManifestV1 {
  manifestVersion: 1;
  uiContractVersion: typeof UI_CONTRACT_VERSION;
  id: string;
  name: string;
  tokens?: Partial<Record<ThemeTokenId, string>>;
  variants?: Partial<Record<ThemeVariantId, ThemeVariantValue>>;
}

export interface ShellUser {
  displayName: string;
  locale: string;
}

export interface ShellApp {
  id: string;
  title: string;
  launchable: boolean;
}

export interface ShellTheme {
  id: string;
  stylesheetUrl: `/shell/themes/sha256-${string}.css`;
  windowChrome: WindowChromeVariant;
  shellLayout: ShellLayoutVariant;
  launcherLayout: LauncherLayoutVariant;
  tokens: Record<string, string>;
}

export type SystemProtectionStatus = "active" | "attention";

export interface ShellSystemStatus {
  protection: SystemProtectionStatus;
  installedAppCount: number;
  observedAtUnixMs: number;
  lastActivityAtUnixMs: number | null;
}

export type ExtensionContribution =
  | {
      kind: "command";
      id: string;
      title: string;
      capability: string;
    }
  | {
      kind: "search_provider";
      id: string;
      title: string;
      capability: string;
    }
  | {
      kind: "widget";
      id: string;
      title: string;
      slot: ExtensionSlot;
      entrypoint: string;
    };

export interface ShellSnapshotV1 {
  snapshotVersion: typeof SNAPSHOT_VERSION;
  uiContractVersion: typeof UI_CONTRACT_VERSION;
  extensionApiVersion: typeof EXTENSION_API_VERSION;
  shellBuildId: string;
  revision: string;
  user: ShellUser;
  theme: ShellTheme;
  apps: readonly ShellApp[];
  workspace: string | null;
  systemStatus: ShellSystemStatus;
  mode: ShellMode;
  contributions: readonly ExtensionContribution[];
}
"#;

pub fn typescript_contracts_v1() -> &'static str {
    TYPESCRIPT_CONTRACTS_V1
}
